# main.yml
# Default runner for 'releases' repository
name: Compile StatiXOS for devices

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        # Let the user decide whether to sync before compilation, or not
        sync:
          description: 'Sync repositories before building'
          type: boolean

        # Let the user decide whether to produce a clean build before compiling, or not
        clean:
          description: 'Produce a clean build'
          type: boolean

        # Make the user choice between a list of devices
        device:
          description: 'Choose device to build for:'
          required: true
          type: choice
          options:
           - 'Xiaomi POCO M6 Pro 5G / Redmi 12 5G / Redmi Note 12R'
           - 'Xiaomi SM7125 family'

        # Make the user choice between a list of package types
        package:
          description: 'Choose type of package to build:'
          required: true
          type: choice
          options:
           - 'Recovery-flashable (otapackage)'
           - 'Bootloader-flashable (updatepackage)'

jobs:
  # Declare the 'sync' job
  sync:
    # Only execute if 'inputs.sync' is set to 'true'
    if: ${{ inputs.sync }}
    # Set our self-hosted runner's labels
    runs-on: [self-hosted, linux, x64]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Execute 'sync.sh'
      - name: Start syncing StatiXOS
        run: ${PWD}/tools/sync.sh
