# main.yml
# Default runner for 'releases' repository
name: Compile StatiXOS for devices

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Declare the 'build' job
  build:
    # Set our self-hosted runner's labels
    runs-on: [self-hosted, linux, x64]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
